src/account/urls.py
from django.conf.urls import url,include
from .views import user_login,register
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'login/$',user_login,name='user_login'),
    url(r'logout/$',auth_views.logout,{'template_name':'account/logout.html'},name='user_logout'),
    url(r'register/$',register,name='register'),
    url(r'password-change/$',auth_views.password_change,{'template_name':'account/password_change.html'},name='password_change'),
    url(r'password-change-done/$',auth_views.password_change_done,{'template_name':'account/password_change_done.html'},name='password_change_done')
]

src/blog/urls.py
from django.conf.urls import url,include
from .views import blog_title,blog_content


urlpatterns = [
    url(r'^$', blog_title,name='blog_title'),
    url(r'(?P<article_id>\d)/$', blog_content,name='blog_title'),
]

src/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^account/', include('account.urls',namespace='account')),
]

src/account/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User,unique=True)
	birth = models.DateTimeField(blank=True,null=True)
	phone = models.CharField(max_length=20,null=True)

	def __str__(self):
		return 'user{}'.format(self.user.username)

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class BlogArticles(models.Model):
	title=models.CharField(max_length=30)
	author=models.ForeignKey(User,related_name='blog_posts')
	body=models.TextField()
	publish=models.DateTimeField(default=timezone.now)

	class Meta:
		ordering=('-publish',)

	def __str__(self):
		return self.title

src/account/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserProfile

User=get_user_model()

class LoginForm(forms.Form):
	username=forms.CharField()
	password=forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
	password=forms.CharField(label="Password",widget=forms.PasswordInput)
	password2=forms.CharField(label='Confirm password',widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=('username','email')
	def clean_password2(self):
		cd=self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError("Sorry,password don't match.")
		return cd['password2']
class UserProfileForm(forms.ModelForm):
	class Meta:
		 model = UserProfile
		 fields = ('phone','birth')


	

src/account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,get_user_model
from .forms import LoginForm,RegisterForm,UserProfileForm
User=get_user_model()
# Create your views here.
def user_login(request):
	if request.method == 'POST':
		login_form=LoginForm(request.POST)
		if login_form.is_valid():
			cd=login_form.cleaned_data
			user=authenticate(username=cd['username'],password=cd['password'])
			if user:
				login(request,user)
				return HttpResponse('Successfully Logged.')
			else:
				return HttpResponse('Sorry,your username and password are not right.')
		else:
			return HttpResponse('Invalid Login.')
	if request.method == 'GET':
		login_form=LoginForm()
		return render(request,'account/login.html',{'form':login_form})


def register(request):
	if request.method == 'POST':
		user_form=RegisterForm(request.POST)
		userprofile_form=UserProfileForm(request.POST)
		if user_form.is_valid()*userprofile_form.is_valid():
			new_user=user_form.save(commit=False)
			new_user.set_password(user_form.cleaned_data['password'])
			new_user.save()
			new_profile = userprofile_form.save(commit=False)
			new_profile.user=new_user
			new_profile.save()
			print('saved')
			return HttpResponse('Successfully')
		else:
			return HttpResponse("Sorry,you can't register.")
	if request.method == 'GET':
		user_form=RegisterForm()
		userprofile_form=UserProfileForm()
		return render(request,'account/register.html',{'form':user_form,'profile':userprofile_form})

src/blog/views.py
from django.shortcuts import render,get_object_or_404

from .models import BlogArticles
# Create your views here.

def blog_title(request):
	articles=BlogArticles.objects.all()
	return render(request,'blog/title.html',{'object_list':articles})
def blog_content(request,article_id):
	article=get_object_or_404(BlogArticles,id=article_id)
	return render(request,'blog/content.html',{'object':article})

src/templates/base.html
{% load staticfiles %}
<html>
	<head>
		<title>{% block head_title %}FindPagnn{% endblock head_title %}</title>
		<link rel='stylesheet' href="{% static 'css/bootstrap.css' %}">
	</head>
	<body>
		{% include 'header.html' %}
		{% block content %}
		{% endblock content %}
		{% include 'footer.html' %}
		<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	</body>
</html>

src/templates/blog/content.html
{% extends 'base.html' %}
{% block head_title %}Blog | {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='container'>
	<div class='row'>
		<div class='col-md-8 col-md-offset-2'>
			<h1>{{ object.title }}</h1>
			<h3>{{ object.author.username }} | {{ object.publish }}</h3>
			<p>{{ object.body }}</p>
		</div>
	</div>
</div>
{% endblock content %}

src/templates/blog/title.html
{% extends 'base.html' %}
{% block head_title %}Blog | {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='container'>
	<div class='row'>
		<div class='col-md-8 col-md-offset-2'>
			<h1>我的博客</h1>
			<div>
				{% for obj in object_list %}
					<a href='{{ obj.id }}'><li>{{ obj.title }}</li></a>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}

src/templates/footer.html
<div class='container'>
	<hr/>
	<p class='text-center'>Copy Right @FindPagnn.</p>
</div>

src/templates/header.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><img src="{% static '/images/test.jpg' %}" style='border-radius:50%;height:50px;width:50px;'></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:blog_title' %}">Blog <span class="sr-only">(current)</span></a>
      </li>    
    </ul>
    <ul class='nav navbar-nav navbar-right'>
            {% if request.user.is_authenticated %}
       <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'account:user_logout' %}">{{ user.username }}</a>
      </li>
            <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
      </li>
      {% else %}

            <li class="nav-item navbar-right">
        <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
      </li>
      {% endif %} 
    </ul>
  </div>
</nav>